/**
 * waves · Drizzle client (bun:sqlite driver).
 *
 * Also holds the row → API-shape mappers, so the wire format is defined in exactly one
 * place and every route returns an identical object for the same entity.
 */

import { Database } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";
import { mkdirSync } from "node:fs";
import { join } from "node:path";

import * as schema from "./schema";
import type { Exercise, Experiment } from "./schema";

// Overridden in the container, where the persistent volume is mounted elsewhere.
export const DATA_DIR = process.env.WAVES_DATA_DIR ?? "./server/data";
mkdirSync(DATA_DIR, { recursive: true });

const sqlite = new Database(join(DATA_DIR, "waves.db"), { create: true });
sqlite.exec("PRAGMA journal_mode = WAL");
sqlite.exec("PRAGMA foreign_keys = ON");

export const db = drizzle(sqlite, { schema });

/** Apply migrations generated by `bun run db:generate`. Safe to call on every boot. */
export function runMigrations() {
  migrate(db, { migrationsFolder: "./server/drizzle" });
}

// --------------------------------------------------------------------------- //
// media paths — files live on disk, only their relative path is stored
// --------------------------------------------------------------------------- //

export const mediaRel = (exerciseId: string, name: string) =>
  join("exercises", exerciseId, name);

export const mediaAbs = (rel: string) => join(DATA_DIR, rel);

export const mediaDir = (exerciseId: string) =>
  join(DATA_DIR, "exercises", exerciseId);

// --------------------------------------------------------------------------- //
// row → API shape
// --------------------------------------------------------------------------- //

export const toExperiment = (r: Experiment) => ({
  id: r.id,
  patientNumber: r.patientNumber,
  height: r.height,
  age: r.age,
  weight: r.weight,
  createdAt: r.createdAt,
  properties: r.properties ?? {},
});

export const toExercise = (r: Exercise, readingCount = 0) => ({
  id: r.id,
  experimentId: r.experimentId,
  createdAt: r.createdAt,
  properties: r.properties ?? {},
  recordingStatus: r.recordingStatus,
  hasData: r.hasData,
  recordingStartedAt: r.recordingStartedAt,
  recordingEndedAt: r.recordingEndedAt,
  readingCount,
  notes: r.notes,
});
